<?php

namespace Lucy\TodolistBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TasksListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasksListRepository extends EntityRepository
{
}
