lucy_todolist:
    resource: "@LucyTodolistBundle/Controller/"
    type:     annotation
    prefix:   /

lucy_voter:
    resource: "@LucyVoterBundle/Controller/"
    type:     annotation
    prefix:   /

lynda_magazine:
    resource: "@LyndaMagazineBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
